services:
  agent:
    build: .
    # Если реплика удаляем container_name: rs_agent_db
    container_name: rs_agent_db
    env_file:
      - .env
# Добавляем блок deploy
#    deploy:
#      mode: replicated
#      replicas: ${REPLICAS:-3} # Запустит 3 по умолчанию, если в .env нет REPLICAS

    healthcheck:
      test: ["CMD", "python", "health_check.py"]
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s
    volumes:
      - ./logs:/rsagent_db/logs
      - shared_media:/app/media
    restart: always
    network_mode: "host"
    stop_grace_period: 45s

volumes:
  shared_media:



#    mkdir logs
#    chmod 777 logs # или chown 999:999 logs
#    docker-compose up -d --build